config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboards#home'
  resources :matches
  resources :teams
  resources :games
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_breadcrumbs.html.erb
<% if content_for?(:breadcrumbs) %>
  <div class="breadcrumb-wrapper">
    <nav class="breadcrumb">
      <%= link_to 'Dashboard', root_path, class: 'breadcrumb-item' %>
      <% breadcrumbs = JSON.parse(sanitize yield(:breadcrumbs)) if content_for?(:breadcrumbs) %>
      <% breadcrumbs.each do |breadcrumb| %>
        <% case breadcrumb.class.to_s %>
      <% when 'Array' %>
          <% string, link = breadcrumb %>
          <%= link_to string, link, class: "breadcrumb-item #{breadcrumb.equal?(breadcrumbs.last) ? 'active' : nil}" %>
        <% when 'String' %>
          <%= content_tag :span, breadcrumb, class: "breadcrumb-item #{breadcrumb.equal?(breadcrumbs.last) ? 'active' : nil}" %>
        <% end %>
      <% end if content_for?(:breadcrumbs) %>
    </nav>
  </div>
<% end %>

app/views/shared/_left_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse slimscrollsidebar">
    <ul class="nav" id="side-menu">
      <li class="sidebar-search hidden-sm hidden-md hidden-lg">
      </li>
      <li class="nav-small-cap m-t-10">--- Main Menu</li>
      <li>
        <%= link_to matches_url, class: "nav-link" do %>
          <span class="hide-menu"> Match</span>
        <% end %>
      </li>
      <li>
        <%= link_to teams_url, class: "nav-link" do %>
          <span class="hide-menu"> Team </span>
        <% end %>
      </li>
      <li>
        <%= link_to games_url, class: "nav-link" do %>
          <span class="hide-menu"> Game</span>
        <% end %>
      </li>
      <li>
        <%= link_to players_url, class: "nav-link" do %>
          <span class="hide-menu"> Player </span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-message fixed-top alert-<%= name.to_s == "notice" ? "success" : "danger" %>" role="alert" style="z-index: 999999999999">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.alert').slideDown(500).delay(3000).slideUp(500);
  })
</script>