config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboards#home'
  resources :matches
  resources :teams
  resources :games
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  has_many :games, dependent: :destroy

  belongs_to :team_1,
             foreign_key: 'team_1_id',
             class_name: 'Team', inverse_of: :matches

  belongs_to :team_2,
             foreign_key: 'team_2_id',
             class_name: 'Team', inverse_of: :matches

  belongs_to :winner_team,
             foreign_key: 'winner_team_id',
             class_name: 'Team', inverse_of: :matches, optional: true

  validates :team_1, :team_2, presence: true
  validates :games, length: { maximum: 3 }
  validates :team_1, uniqueness: { scope: :team_2 }
  validates :team_1, exclusion: { in: lambda{ |match| [match.team_2] } }
  validate :match_data_cant_change_if_completed, on: :update

  delegate :name, to: :winner_team, prefix: true
  scope :by_team, lambda{ |team_id| where(team_1_id: team_id).or(where(team_2_id: team_id)) if team_id }
  scope :completed, -> { where.not(winner_team_id: nil) }
  scope :not_completed, -> { where.not(id: completed) }

  private

  def match_data_cant_change_if_completed
    return if winner_team_id_was.nil?

    errors.add(:base, 'Match already completed!') if winner_team_id
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %w[show edit update destroy]

  # GET /matches
  def index
    @matches = Match.all
  end

  # GET /matches/1
  def show; end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit; end

  # POST /matches
  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to @match, notice: 'Match was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /matches/1.json
  def update
    if @match.update(match_params)
      redirect_to @match, notice: 'Match was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /matches/1
  def destroy
    @match.destroy
    redirect_to matches_url, notice: 'Match was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def match_params
    params.require(:match).permit(:team_1_id, :team_2_id)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(match.errors.count, 'error') %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='form-group'>
    <%= form.label :team_1, 'Team 1:' %>
    <%= form.select 'team_1_id', options_for_select(Team.all.collect{ |u| [u.name, u.id] }, match.team_1_id), {}, { class: 'form-control' }  %>
  </div>
  <div class='form-group'>
    <%= form.label :team_2, 'Team 2:' %>
    <%= form.select 'team_2_id', options_for_select(Team.all.collect{ |u| [u.name, u.id] }, match.team_2_id), {}, { class: 'form-control' } %>
  </div>

  <div class='actions'>
    <%= form.submit 'Submit' , class: 'btn btn-outline btn-success btn-lg' %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>ID</th>
            <th>Team 1</th>
            <th>Team 2</th>
            <th>Winner Team</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
          <% @matches.each do |match| %>
            <tr>
              <td><%= match.id %></td>
              <td><%= match.team_1.name %></td>
              <td><%= match.team_2.name %></td>
              <td><%= match.winner_team&.name %></td>
              <td>
                <%= link_to edit_match_path(match), class: "btn btn-outline btn-info" do %>
                  Edit
                <% end %>
                <%= link_to 'Destroy', match, method: :delete, class: "btn btn-danger btn-outline", data: { confirm: 'Are you sure?' } %>

              </td>
            </tr>
          <% end if @matches.any? %>
          </tbody>
        </table>
        <%= link_to "Add new", new_match_path, class: "btn btn-outline btn-success float-right" %>
      </div>
    </div>
  </div>
</div>

<br>
<% content_for :page_name do %>
  <%= "Matches" %>
<% end %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>